---
- hosts: terraform-testing
  become: true
  vars:
    - terraform_version: "0.11.7"
    - awscli_pip_package: "python-pip"
    - awscli_version: "1.11.73"
  roles:
  - secfigo.terraform 
  - tommarshall.awscli       
